meta:
  version: 0.0.1
  engine: 4.1.0
  author: Etash Jhanji
units:
  $default_padding: cy
  px: cx+5
  py: cy+5
points: 
  zones: 
    leftmain: 
      columns: 
        pinky: 
          key.splay: 8
          key.origin: [-20, 15]
          key.column_net: P022
        ring: 
          key.stagger: 14
          key.splay: -7
          key.spread: cx + 2
          key.column_net: P024
        middle: 
          key.splay: -5
          key.spread: cx+2
          key.stagger: 4
          key.column_net: P100
        index:
          key.splay: -5
          key.stagger: -5
          key.spread: cx+1
          key.column_net: P011
        indexfar:
          key.splay: -1
          key.stagger: 0
          key.column_net: P104
      rows: 
        bottom:
          row_net: P031
        home:
          row_net: P029
        top:
          row_net: P002
      anchor: 
        shift: [85, -150]
    leftthumb: 
      anchor: 
        ref: leftmain_indexfar_bottom
        shift: [-7, -20]
      columns:
        in: 
          key.column_net: P022
        home: 
          key.splay: -20
          key.shift: [4, -2]
          key.column_net: P024
        out: 
          key.splay: -23
          key.shift: [9, -3]
          key.column_net: P100
      rows: 
        thumb: 
          key.splay: 6
          key.row_net: P115
    leftthumbfar: 
      anchor: 
        ref: leftthumb_home_thumb
      columns: 
        in: 
          key.column_net: P011
        out: 
          key.splay: -23
          key.shift: [0, cy-2]
          key.column_net: P104
      key: 
        shift: [3, cy+1]
        row_net: P115
  mirror: 
    ref: leftmain_pinky_home
    distance: 270
outlines: 
  raw: 
    - what: rectangle
      where: true
      size: [cx, cy]
  keys: 
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  board_left: 
    - what: polygon
      operation: stack
      points: 
        - ref: leftmain_pinky_top
          shift: [-0.5px,0.5py]
        - ref: leftmain_ring_top
          shift: [-0.5px,0.5py]
        - ref: leftmain_middle_top
          shift: [-0.5px,0.5py]
        - ref: leftmain_middle_top
          shift: [0.5px,0.5py]
        #- ref: leftmain_index_top
        #  shift: [0.5px,0.5py]
        - ref: leftmain_indexfar_top
          shift: [0.5px + 21,0.5py]
        - ref: leftmain_indexfar_top
          shift: [0.5px + 20,0.5py-36]
        - ref: leftthumbfar_in
          shift: [0.15px,0.5py]
        - ref: leftthumbfar_out
          shift: [-0.5px,0.5py]
        - ref: leftthumbfar_out
          shift: [0.5px,0.5py]
        - ref: leftthumb_out_thumb
          shift: [0.5px,0.5py]
        - ref: leftthumb_out_thumb
          shift: [0.5px,-0.5py]
        #- ref: leftthumb_out_thumb
        #  shift: [-0.5px,-0.5py]
        - ref: leftthumb_home_thumb
          shift: [0.5px-1,-0.5py]
        - ref: leftthumb_home_thumb
          shift: [-0.5px+1,-0.5py]
        - ref: leftthumb_in_thumb
          shift: [-0.5px,-0.5py]
        - ref: leftmain_middle_bottom
          shift: [0px,-0.5py]
        - ref: leftmain_ring_bottom
          shift: [0.5px,-0.5py]
        - ref: leftmain_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: leftmain_pinky_bottom
          shift: [-0.5px,-0.5py]
      fillet: 5
  board_right: 
    - what: polygon
      operation: stack
      points: 
        - ref: mirror_leftmain_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_leftmain_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_leftmain_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_leftmain_middle_top
          shift: [0.5px,0.5py]
        #- ref: mirror_leftmain_index_top
        #  shift: [0.5px,0.5py]
        - ref: mirror_leftmain_indexfar_top
          shift: [0.5px + 21,0.5py]
        - ref: mirror_leftmain_indexfar_top
          shift: [0.5px + 20,0.5py-36]
        - ref: mirror_leftthumbfar_in
          shift: [0.15px,0.5py]
        - ref: mirror_leftthumbfar_out
          shift: [-0.5px,0.5py]
        - ref: mirror_leftthumbfar_out
          shift: [0.5px,0.5py]
        - ref: mirror_leftthumb_out_thumb
          shift: [0.5px,0.5py]
        - ref: mirror_leftthumb_out_thumb
          shift: [0.5px,-0.5py]
        #- ref: mirror_leftthumb_out_thumb
        #  shift: [-0.5px,-0.5py]
        - ref: mirror_leftthumb_home_thumb
          shift: [0.5px-1,-0.5py]
        - ref: mirror_leftthumb_home_thumb
          shift: [-0.5px+1,-0.5py]
        - ref: mirror_leftthumb_in_thumb
          shift: [-0.5px,-0.5py]
        - ref: mirror_leftmain_middle_bottom
          shift: [0px,-0.5py]
        - ref: mirror_leftmain_ring_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_leftmain_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_leftmain_pinky_bottom
          shift: [-0.5px,-0.5py]
      fillet: 5
  board_full: 
    - name: board_left
    - operation: add
      name: board_right
  combo: 
    - name: board_left
    - operation: add
      name: board_right
    - operation: subtract
      name: keys
#cases: <case config...> #optional
pcbs:
  banana_split: 
    outlines: 
      main: 
        outline: board_full
    footprints: 
      choc_hotswap:
        what: choc
        where: true
        params: 
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params: 
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust: 
          shift: [0, -5]
      nicenano_left: 
        what: nicenano 
        params: 
          orientation: "up"
        where: 
          ref: leftmain_indexfar_top
          shift: [px-2,-0.55cy]
          rotate: -92
      nicenano_right: 
        what: nicenano 
        params: 
          orientation: "up"
          RAW: RRAW
          GND: RGND
          RST: RRST
          VCC: RVCC
          P031: RP031
          P029: RP029
          P002: RP002
          P115: RP115
          P113: RP113
          P111: RP111
          P010: RP010
          P009: RP009
          P006: RP006
          P008: RP008
          P017: RP017
          P020: RP020
          P022: RP022
          P024: RP024
          P100: RP100
          P011: RP011
          P104: RP104
          P106: RP106
          P101: RP101
          P102: RP102
          P107: RP107
        where: 
          ref: mirror_leftmain_indexfar_top
          shift: [px-2,-0.55cy]
          rotate: 88
      niceview_left: 
        what: niceview 
        params: 
          CS: P006
          SCK: P020
          MOSI: P017
          pin_socket_3dmodel_filename: '${BANANA_SPLIT}/models/fem5pin.step'
          pin_socket_3dmodel_xyz_rotation: [90, 0,0]
          pin_socket_3dmodel_xyz_offset: [-5, -16.75, 0]
          pin_header_3dmodel_filename: '${BANANA_SPLIT}/models/mal5pin.step'
          pin_header_3dmodel_xyz_rotation: [180, 0,0]
          pin_header_3dmodel_xyz_offset: [-5, -16.75, 8]
          niceview_3dmodel_filename: '${BANANA_SPLIT}/models/niceview.step'
          niceview_3dmodel_xyz_rotation: [0, 0,90]
          niceview_3dmodel_xyz_offset: [0, 0,9.5]
        where: 
          ref: leftmain_indexfar_top
          shift: [px-2,-0.57cy]
          rotate: -2
      niceview_right: 
        what: niceview 
        params: 
          CS: RP006
          SCK: RP020
          MOSI: RP017
          VCC: RVCC
          GND: RGND
          pin_socket_3dmodel_filename: '${BANANA_SPLIT}/models/fem5pin.step'
          pin_socket_3dmodel_xyz_rotation: [90, 0,0]
          pin_socket_3dmodel_xyz_offset: [-5, -16.75, 0]
          pin_header_3dmodel_filename: '${BANANA_SPLIT}/models/mal5pin.step'
          pin_header_3dmodel_xyz_rotation: [180, 0,0]
          pin_header_3dmodel_xyz_offset: [-5, -16.75, 8]
          niceview_3dmodel_filename: '${BANANA_SPLIT}/models/niceview.step'
          niceview_3dmodel_xyz_rotation: [0, 0,90]
          niceview_3dmodel_xyz_offset: [0, 0,9.5]
        where: 
          ref: mirror_leftmain_indexfar_top
          shift: [px-2,-0.57cy]
          rotate: -2 
      jstph_left: 
        what: jstph 
        params:
          side: 'B'
          reversible: true
          BAT_P: RAW
          battery_connector_3dmodel_filename: '${BANANA_SPLIT}/models/jstph.stp'
          battery_connector_3dmodel_xyz_offset: [0, -2, 0]
        where: 
          ref: leftmain_index_bottom
          shift: [-0.1px,-0.7cy]
      jstph_right: 
        what: jstph 
        params:
          side: 'B'
          reversible: true
          BAT_P: RRAW
          BAT_N: RGND
          battery_connector_3dmodel_filename: '${BANANA_SPLIT}/models/jstph.stp'
          battery_connector_3dmodel_xyz_offset: [0, -2, 0]
        where: 
          ref: mirror_leftmain_index_bottom
          shift: [-0.1px,-0.7cy]
      reset_left: 
        what: button
        params: 
          from: GND
          to: RST
        where: 
          ref: leftmain_ring_top
          shift: [-0.7px, -2]
          rotate: 6
      reset_right: 
        what: button
        params: 
          from: RGND
          to: RRST
        where: 
          ref: mirror_leftmain_ring_top
          shift: [-0.7px, -2]
          rotate: 6
