meta:
  version: 0.0.1
  engine: 4.1.0
  author: Etash Jhanji
units:
  $default_padding: cy
  px: cx+5
  py: cy+5
points: 
  zones: 
    leftmain: 
      columns: 
        pinky: 
          key.splay: 8
          key.origin: [-20, 15]
        ring: 
          key.stagger: 14
          key.splay: -7
          key.spread: cx + 2
        middle: 
          key.splay: -5
          key.spread: cx+2
          key.stagger: 4
        index:
          key.splay: -5
          key.stagger: -5
          key.spread: cx+1
        indexfar:
          key.splay: -1
          key.stagger: 0
      rows: 
        bottom:
        home:
        top:
      anchor: 
        shift: [85, -150]
    leftthumb: 
      anchor: 
        ref: leftmain_indexfar_bottom
        shift: [-7, -20]
      columns:
        in: 
        home: 
          key.splay: -20
          key.shift: [4, -2]
        out: 
          key.splay: -23
          key.shift: [9, -3]
      rows: 
        thumb: 
          key.splay: 6
    leftthumbfar: 
      anchor: 
        ref: leftthumb_home_thumb
      columns: 
        in: 
        out: 
          key.splay: -23
          key.shift: [0, cy-2]
      key: 
        shift: [3, cy+1]
  mirror: 
    ref: leftmain_pinky_home
    distance: 270
outlines: 
  raw: 
    - what: rectangle
      where: true
      size: [cx, cy]
  keys: 
    - what: rectangle
      where: true
      size: [cx-0.5, cy-0.5]
  board_left: 
    - what: polygon
      operation: stack
      points: 
        - ref: leftmain_pinky_top
          shift: [-0.5px,0.5py]
        - ref: leftmain_ring_top
          shift: [-0.5px,0.5py]
        - ref: leftmain_middle_top
          shift: [-0.5px,0.5py]
        - ref: leftmain_middle_top
          shift: [0.5px,0.5py]
        #- ref: leftmain_index_top
        #  shift: [0.5px,0.5py]
        - ref: leftmain_indexfar_top
          shift: [0.5px + 21,0.5py]
        - ref: leftmain_indexfar_top
          shift: [0.5px + 20,0.5py-36]
        - ref: leftthumbfar_in
          shift: [0.15px,0.5py]
        - ref: leftthumbfar_out
          shift: [-0.5px,0.5py]
        - ref: leftthumbfar_out
          shift: [0.5px,0.5py]
        - ref: leftthumb_out_thumb
          shift: [0.5px,0.5py]
        - ref: leftthumb_out_thumb
          shift: [0.5px,-0.5py]
        #- ref: leftthumb_out_thumb
        #  shift: [-0.5px,-0.5py]
        - ref: leftthumb_home_thumb
          shift: [0.5px-1,-0.5py]
        - ref: leftthumb_home_thumb
          shift: [-0.5px+1,-0.5py]
        - ref: leftthumb_in_thumb
          shift: [-0.5px,-0.5py]
        - ref: leftmain_middle_bottom
          shift: [0px,-0.5py]
        - ref: leftmain_ring_bottom
          shift: [0.5px,-0.5py]
        - ref: leftmain_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: leftmain_pinky_bottom
          shift: [-0.5px,-0.5py]
      fillet: 5
  board_right: 
    - what: polygon
      operation: stack
      points: 
        - ref: mirror_leftmain_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_leftmain_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_leftmain_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_leftmain_middle_top
          shift: [0.5px,0.5py]
        #- ref: mirror_leftmain_index_top
        #  shift: [0.5px,0.5py]
        - ref: mirror_leftmain_indexfar_top
          shift: [0.5px + 21,0.5py]
        - ref: mirror_leftmain_indexfar_top
          shift: [0.5px + 20,0.5py-36]
        - ref: mirror_leftthumbfar_in
          shift: [0.15px,0.5py]
        - ref: mirror_leftthumbfar_out
          shift: [-0.5px,0.5py]
        - ref: mirror_leftthumbfar_out
          shift: [0.5px,0.5py]
        - ref: mirror_leftthumb_out_thumb
          shift: [0.5px,0.5py]
        - ref: mirror_leftthumb_out_thumb
          shift: [0.5px,-0.5py]
        #- ref: mirror_leftthumb_out_thumb
        #  shift: [-0.5px,-0.5py]
        - ref: mirror_leftthumb_home_thumb
          shift: [0.5px-1,-0.5py]
        - ref: mirror_leftthumb_home_thumb
          shift: [-0.5px+1,-0.5py]
        - ref: mirror_leftthumb_in_thumb
          shift: [-0.5px,-0.5py]
        - ref: mirror_leftmain_middle_bottom
          shift: [0px,-0.5py]
        - ref: mirror_leftmain_ring_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_leftmain_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_leftmain_pinky_bottom
          shift: [-0.5px,-0.5py]
      fillet: 5
  board_full: 
    - name: board_left
    - operation: add
      name: board_right
  combo: 
    - name: board_left
    - operation: add
      name: board_right
    - operation: subtract
      name: keys
#cases: <case config...> #optional
pcbs:
  banana_split: 
    outlines: 
      main: 
        outline: board_full
    footprints: 
      choc_hotswap:
        what: choc
        where: true
        params: 
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params: 
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust: 
          shift: [0, -5]
      nicenano: 
        what: nicenano 
        params: 
          orientation: "down"
        where: 
          ref: leftmain_indexfar_top
          shift: [0,0]
          rotate: 0
